'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pokemon_Catch_Rate_Calc.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Dive_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Dive_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Dusk_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Dusk_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Fast_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Fast_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Friend_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Friend_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Great_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Great_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Heal_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Heal_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Heavy_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Heavy_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Level_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Level_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Love_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Love_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Lure_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Lure_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Luxury_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Luxury_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Master_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Master_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Moon_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Moon_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Nest_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Nest_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Net_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Net_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Poké_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Poké_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Premier_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Premier_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Quick_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Quick_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Repeat_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Repeat_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Safari_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Safari_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Sport_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Sport_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Timer_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Timer_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bag_Ultra_Ball_Sprite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bag_Ultra_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Dream_Master_Ball_Sprite() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Dream_Master_Ball_Sprite", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RBY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RBY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WooperZ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WooperZ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
